_schema: _schema
paths:
  uploads: public/uploads
  static: public
collections_config:
  2022_07_08_first_post:
    path: src/content/blog/2022-07-08-first-post
    name: 2022 07 08 First Post
    icon: first_page
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  2022_07_15_second_post:
    path: src/content/blog/2022-07-15-second-post
    name: 2022 07 15 Second Post
    icon: compost
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  2022_07_2_third_post:
    path: src/content/blog/2022-07-2-third-post
    name: 2022 07 2 Third Post
    icon: local_airport
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  2023_08_16_sagittis_purus:
    path: src/content/blog/2023-08-16-sagittis-purus
    name: 2023 08 16 Sagittis Purus
    icon: sanitizer
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  2023_08_17_lorem_ipsum:
    path: src/content/blog/2023-08-17-lorem-ipsum
    name: 2023 08 17 Lorem Ipsum
    icon: workspace_premium
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  2024_08_17_using_mdx:
    path: src/content/blog/2024-08-17-using-mdx
    name: 2024 08 17 Using Mdx
    icon: add_business
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  2024_08_18_markdown_style_guide:
    path: src/content/blog/2024-08-18-markdown-style-guide
    name: 2024 08 18 Markdown Style Guide
    icon: arrow_circle_up
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
    disable_url: true
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_enabled_editors:
  - content
  - data
  - visual
timezone: Europe/Podgorica
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
